FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src
COPY ["RapidRecruit.csproj", "./"]
RUN dotnet restore
COPY . .
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"
ENTRYPOINT ["dotnet", "ef", "database", "update"]

