name: Docker Build and Push

on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
 build:
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v4
   
   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
       
   - name: Build and push app image
     uses: docker/build-push-action@v5
     with:
       context: ./RapidRecruit
       file: ./RapidRecruit/Dockerfile
       push: true
       tags: lukakaralic/rapidrecruit:latest
       
   - name: Build and push migrations image  
     uses: docker/build-push-action@v5
     with:
       context: ./RapidRecruit
       file: ./RapidRecruit/Dockerfile.migrations
       push: true
       tags: lukakaralic/rapidrecruit-migrations:latest
